name: Build and test eshop workflow

on:
  workflow_dispatch:
  push: 

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN_SEM  }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10

      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install packages with npm
        run: |
          npm ci

  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN_SEM  }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10

      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors

      - name: Cache node modules and build folder
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/cache@v3.0.11
        with: 
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-build-${{ github.run_id }}

  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v2.5.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN_SEM }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 10

      - name: Cache node modules
        uses: actions/cache@v3.0.11
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        run: |
          npm run test -- --colors

  Deploy:
    needs: [Build, Test]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get project files from GIT
        run: git clone https://github.com/jsoos/4IT572_sem.git

      #- name: Vault
      #  run: |
      #    cd 4IT572_sem
      #    ansible-vault create group_vars/all/aws.yml


      - name: Install
        run: pip3 install ansible boto boto3
      - name: Install AWS
        run: ansible-galaxy collection install amazon.aws
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: 4IT572_sem/deploy.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --extra-vars access_key=${{ secrets.ACCESS_KEY }} secret_key=${{ secrets.SECRET_KEY }} session_token=${{ secrets.SESSION_TOKEN }}

          #vault_password: ${{secrets.VAULT_PASSWORD}}


      #- name: Run playbook
      #  run: ansible-playbook 4IT572_sem/deploy.yml




